Update CredentialsGitHubOptions
IBM-Swift/Kitura-CredentialsGitHub pull request #22
Opened 2016-12-13 15:39 UTC by haldun

Fixed the comments.

2016-12-13 15:40 UTC, ianpartridge requested changes

2016-12-13 15:40 UTC, ianpartridge commented on Sources/CredentialsGitHub/CredentialsGitHubOptions.swift
> +/// A list of options for authentication with Github.
Should be `GitHub`.

2016-12-13 16:11 UTC, ianpartridge commented
Thanks for your PR!  Have you submitted a [CLA](https://github.com/IBM-Swift/CLA)? If not, please do - it's a one-time thing which lets you contribute to all Swift@IBM projects.

2016-12-15 16:13 UTC, youming-lin commented
@haldun Have you submitted the CLA yet? Please let us know here so we can decide on merging this PR for the next release.

2019-06-28 09:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM-Swift/Kitura-CredentialsGitHub?pullRequest=22) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM-Swift/Kitura-CredentialsGitHub?pullRequest=22) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM-Swift/Kitura-CredentialsGitHub?pullRequest=22) it.</sub>

2019-06-28 09:37 UTC, ianpartridge commented
Already fixed.

2019-06-28 09:37 UTC, closed without merging